// <auto-generated />
namespace WebApplication2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddCouponSupport : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCouponSupport));
        
        string IMigrationMetadata.Id
        {
            get { return "202505111332221_AddCouponSupport"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
